name: PUBLISH TO NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Commit changes before version bump" || echo "No changes to commit"

      - name: Check and validate version
        id: version_check
        run: |
          chmod +x ./scripts/check-version.sh
          ./scripts/check-version.sh

      - name: Bump version and create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          
          if [ "${{ steps.version_check.outputs.should_bump }}" = "true" ]; then
            echo "Bumping version to ${{ steps.version_check.outputs.target_version }}"
            npm version "${{ steps.version_check.outputs.target_version }}" --force -m "Bump version to %s"
          else
            echo "Creating tag for existing version ${{ steps.version_check.outputs.target_version }}"
            git tag -a -f "v${{ steps.version_check.outputs.target_version }}" -m "Tag version ${{ steps.version_check.outputs.target_version }}"
          fi
          
          git push origin main --tags --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: |
          echo "Publishing version ${{ steps.version_check.outputs.target_version }} to npm..."
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
